# Generated by Django 2.2 on 2019-05-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190517_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount transferred')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Transference time')),
                ('recorded_balance', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Recorded balance')),
                ('concept', models.TextField(blank=True, verbose_name='Transference concept')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='api.Account', verbose_name='Receiver account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='api.Account', verbose_name='Sender account')),
            ],
        ),
    ]
